name: Test Docker Push

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test simple build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-${{ github.run_number }}
        platforms: linux/amd64

    - name: Verify push
      run: |
        echo "✅ Test image pushed successfully!"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-${{ github.run_number }}"
        echo ""
        echo "You can pull it with:"
        echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-${{ github.run_number }}"

    - name: Cleanup test image
      run: |
        echo "Note: Test images should be manually deleted from the package registry"
        echo "Go to: https://github.com/${{ github.repository }}/pkgs/container/${{ github.event.repository.name }}"